### PR TITLE
Update jsutilities

### PR DESCRIPTION
**Pull request by rt-jar**
I had done some changes in getDateDifference.

### CODE REVIEW

**Comment by buggy-programmer** [comment]
If d1 and d2 are instance of date then the check is valid what if someone wants to supply date (d1, d2) in string format? Function itself uses Date function of js to convert d1 and d2 to instance of date, so it takes care of that, therefore the additional check is not required here.

Thanks for your feedback its always welcome

**Comment by rt-jar** [comment]
String is always very difficult to pass on in such cases. Please read definition of pure functions.

**Comment by buggy-programmer** [comment]
Thanks for your input but on the contrary i think differently and that check is not appropriate for the following reasons

1 I/O are in string format, actual data is always in string format so it is easier to use it in a pure form and need not make an object just to compare data.
2 Why one should limit a function to use only an object when one can use it in string format as well in addition to object this gives more flexibility in using the function.
3 Second return of the function already converts both d1, d2 variable into Date object before and then perform the operations on it, so this check is totally invalid 
4 I know pure function def but it doesn't says that you should not be using it at all even the cases where it can be used and which can provide more feasibility to the function/solution.

Thanks for your valuable inputs and its always welcome its always a good learning in this type of discussion

**Comment by rt-jar** [comment]
Well said buggy programmer. It is nice to have these kind of solutions. But it is useful only when you specify how to use it.

I think unit tests or some example will do the needful.

**Pull request closed without merging**
